apiVersion: v1
kind: Secret
metadata:
  name: hf-token
  namespace: default
  labels:
    app: my-inference
type: Opaque
stringData:
  # TODO: trage hier deinen Hugging Face Token ein (hf_...)
  token: "CHANGE_ME_HF_TOKEN"
