apiVersion: v1
kind: Secret
metadata:
  name: proxy-ca
  namespace: default
type: Opaque
stringData:
  proxy-ca.pem: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_CA_BUNDLE
    -----END CERTIFICATE-----
