apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: default
  labels:
    app: my-inference
type: Opaque
stringData:
  # TODO: trage hier deinen S3 Endpoint ein (z.B. https://minio.example.com)
  endpoint: "CHANGE_ME_ENDPOINT"
  # TODO: trage hier deinen S3 Bucket Namen ein
  bucket: "CHANGE_ME_BUCKET"
  # TODO: trage hier deine S3 Region ein (z.B. eu-central-1)
  region: "CHANGE_ME_REGION"
  # TODO: trage hier den S3 Prefix ein, unter dem die Modelle gespeichert werden sollen
  prefix: "CHANGE_ME_PREFIX"
  # TODO: ob SSL-Verifizierung f√ºr S3 aktiviert ist ("true"/"false")
  verify_ssl: "CHANGE_ME_VERIFY_SSL"
  # TODO: trage hier deinen S3 Access Key ein
  access_key: "CHANGE_ME_ACCESS_KEY"
  # TODO: trage hier deinen S3 Secret Key ein
  secret_key: "CHANGE_ME_SECRET_KEY"
